project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/vfdb-info/
  title: "VerbundFDB-info"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/vfdb-info/
  repo-actions: [issue]
  navbar:
    search: true
    logo: IQB-klein.png
  page-footer:
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - icon: IQB-klein.png
        href: index.qmd
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - href: index.qmd
        text: Start
      - section: "Einführung"
        contents:
          - href: intro/what_is.qmd
            text: Was ist VerbundFDB?
          - href: intro/literature.qmd
            text: Literaturquellen

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
