---
lang: de
title: Im Einzelnen
---

Es gibt folgende kontrollierte Vokabularien (sog. CVs) des VerbundFDB im Bereich der Bildungsforschung:

* [VerbundFDB - Kontrolliertes Vokabular - Auswahlverfahren](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/av/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Datenformat](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/df/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Datentyp](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/dt/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Erhebungsdesign](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/ed/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Erhebungseinheit](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/ee/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Erhebungsmethode](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/em/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Forschungsdesign](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/fd/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Forschungsgebiet](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/fg/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Themenbereiche](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/tb/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Erhebungsverfahren](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/v2/index.html)
* [VerbundFDB - Kontrolliertes Vokabular - Zugriff](https://skohub.io/iqb-vocabs/v85/heads/master/w3id.org/iqb/v85/zu/index.html)

Visualisiert kann man sich diese [hier anschauen](https://www.iqb.hu-berlin.de/fdz/browser)Mit den kontrollierten Vokabularien werden auch Harmonisierungsprozesse zwischen Forschungsdatenzentren unterstützt.

Die internationale Anschlussfähigkeit wird durch eine durchgängige Mehrsprachigkeit der Kataloge und Vokabularien ermöglicht sowie durch Informationen zum Mapping einzelner Elemente auf existierende Schemata. Die Kataloge werden aktuell gehalten und bei Weiterentwicklungen werden die nötigen Anpassungen vorgenommen.