---
title: "Einführung in VerbundFDB"
lang: de
---

Im Verbund Forschungsdaten Bildung (VerbundFDB) arbeiten einschlägige nationale Einrichtungen aus dem Bereich der Bildungsforschung und der Forschungsdateninfrastruktur gemeinsam daran, ein attraktives und qualitativ hochwertiges Angebot an Forschungsdaten für die empirische Bildungsforschung bereitzustellen. Dabei verpflichtet sich der VerbundFDB den Prinzipien von Open Science. Forschende finden beim VerbundFDB die Möglichkeit, selbstgenerierte Daten zu archivieren und Forschungsdaten zur Nachnutzung aufzufinden.

Seit 2022 ist der VerbundFDB eine dauerhaft verstetigte Infrastruktur für die Bildungsforschung. Die VerbundFDB-Koordinierungsstelle ist am DIPF | Leibniz-Institut für Bildungsforschung und Bildungsinformation angesiedelt und wird somit von Bund und Ländern finanziert. Die hierüber finanzierten Basisdienste des VerbundFDB werden durch die Partnerinstitutionen GESIS, IQB und DIPF betrieben. Das Forschungsdatenzentrum des IQB, als ein Partner des VerbundFDB, beschäftigt sich dabei insbesondere mit der Archivierung, Dokumentation und Sichtbarmachung der Daten aus Studien mit Kompetenzmessungen. Darüber hinaus sind insgesamt 13 Institutionen am erweiterten Partnernetzwerk beteiligt (z. B. FDZ-DZHW, FDZ-LIfBi, FDZ-Lex, Qualiservice).

Der VerbundFDB trägt dazu bei, das Potenzial der in der Bildungsforschung generierten Forschungsdaten möglichst umfassend auszuschöpfen und eine Kultur des Data Sharing zu etablieren. Bildungsforscher*innen aller Disziplinen können nutzerfreundlich und standortunabhängig auf qualitätsgesicherte Forschungsdaten zugreifen. Bei Wahrung ethischer, datenschutz- und urheberrechtlicher Interessen werden hierdurch Forschungsansätze über disziplinäre und nationale Grenzen hinweg möglich. Es entstehen neue Forschungspotenziale durch hochwertige Forschungsdaten und neue Verknüpfungsmöglichkeiten von Forschungsdaten verschiedener Quellen.

Als zentrale Anlaufstelle für Forschungsdaten in der Bildungsforschung bietet der VerbundFDB folgende Leistungen:

* Sichtbarkeit und Auffindbarkeit von Forschungsdaten: Über die Datensuche sind Forschungsdaten verschiedener Datenzentren und Repositorien recherchierbar;
* Publikation und Erhalt von qualitätsgesicherten Forschungsdaten: Datenbestände werden bei einem inhaltlich und methodisch passenden Datenzentrum unter Wahrung ethischer, datenschutz- und urheberrechtlicher sowie dokumentarischer Standards archiviert und zugänglich gemacht (Daten teilen);
* Schulung und Beratung zum Datenmanagement: In Vorortschulungen, digitalen Schulungs- und Informationsangeboten sowie durch Handreichungen werden Themen des Forschungsdatenmanagements aufbereitet und diskutiert (Daten managen). Projektspezifische Fragen können in individuellen Beratungen vertieft werden.
* Der VerbundFDB arbeitet in enger Partnerschaft mit KonsortSWD und versteht sich als Teil der Nationalen Forschungsdateninfrastruktur (nfdi).
